POST http://localhost:10222/timestamps/create
Content-Type: application/json

{
    "password": "admin"
}

###

GET http://localhost:10222/timestamps/lastCommitTime

###

POST http://localhost:10222/timestamps/countInMonth
Content-Type: application/json

{
    "year": "2020",
    "month": "3"
}

###

POST http://localhost:10222/timestamps/countInYear
Content-Type: application/json

{
    "year": "2020"
}

###

POST http://localhost:10222/timestamps/findMonth
Content-Type: application/json

{
    "year": "2020",
    "month": "3"
}

###

POST http://localhost:10222/timestamps/findYear
Content-Type: application/json

{
    "year": "2020"
}
