POST http://localhost:10222/timestamps/create
Content-Type: application/json

{
    "password": "admin",
    "year": "y2",
    "month": "m1",
    "time": "t1"
}

###

POST http://localhost:10222/timestamps/findMonth
Content-Type: application/json

{
    "year": "y1",
    "month": "m2"
}

###

POST http://localhost:10222/timestamps/findYear
Content-Type: application/json

{
    "year": "y2"
}
